### ISSUE TITLE
feature/new-theme update base installation (smarty, gettext, redis)

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website-docker-base#1]
Once [feature/new-theme](https://github.com/geokrety/geokrety-website/tree/feature/new-theme) will be merged:
- [ ] smarty and gettext installations must be removed from Dockerfile installation steps (now installed using composer)
- [x] check if redis extension is needed

**Comment by kumy** [comment]
`redis` is now required as I use `$_SESSION` and the website docker image has a scale of 2, which  permit upgrading containers without service disruption.

**Comment by boly38** [comment]
I think php73 is already ok
