### ISSUE TITLE
Switch to nginx?

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website-docker-base#4]
Maybe it's worth to take a look to switching to nginx + php-fpm? Especially if yet another bunch of migration activities are coming...

**Comment by kumy** [comment]
This will not help in a short time and will only complicate the infrastructure once more. We've already experienced it on GKM. Don't want to reproduce the experience again.

It would need 2 distinct containers, and share many directories again and at different path in 3 containers (nginx, php-fpm, cdn).

More over, in the long term, current "legacy" website should be replaced by a full api (written in python) + a new frontend using only the api (written using a high level javascript framework)
